version: '3'

services:
  mysql:
    container_name: upper_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "upper"
      MYSQL_PASSWORD: "upper"
      MYSQL_DATABASE: "upper"
      MYSQL_ROOT_PASSWORD: "upper"
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
