version: '3'

services:
  postgresql:
    container_name: upper_postgresql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "upper"
      POSTGRES_PASSWORD: "upper"
      POSTGRES_DB: "upper"
    ports:
      - "5432:5432"
